### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by mattalxndr** [Gabisonfire/raincoat#25]
I think you need to update your tabulate dependency.

```shell
~ % python -m venv ~/raincoat-venv
~ % ~/raincoat-venv/bin/pip install raincoat-jackett
Collecting raincoat-jackett
Using cached raincoat_jackett-1.3.1-py3-none-any.whl
Collecting tabulate==0.8.7
Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting transmission-clutch==6.0.2
Using cached transmission_clutch-6.0.2-py3-none-any.whl (27 kB)
Collecting deluge-client==1.8.0
Using cached deluge_client-1.8.0-py2.py3-none-any.whl (11 kB)
Collecting python-qbittorrent==0.4.2
Using cached python_qbittorrent-0.4.2-py3-none-any.whl
Collecting requests==2.23.0
Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting justlog
Using cached justlog-0.1.1.5-py3-none-any.whl
Collecting colorama==0.4.3
Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting idna<3,>=2.5
Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting chardet<4,>=3.0.2
Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting pydantic<2.0,>=1.4
Using cached pydantic-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
Collecting typing-extensions>=3.7.4.3
Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Installing collected packages: tabulate, deluge-client, chardet, urllib3, typing-extensions, idna, colorama, certifi, requests, pydantic, transmission-clutch, python-qbittorrent, justlog, raincoat-jackett
Successfully installed certifi-2022.6.15 chardet-3.0.4 colorama-0.4.3 deluge-client-1.8.0 idna-2.10 justlog-0.1.1.5 pydantic-1.9.2 python-qbittorrent-0.4.2 raincoat-jackett-1.3.1 requests-2.23.0 tabulate-0.8.7 transmission-clutch-6.0.2 typing-extensions-4.3.0 urllib3-1.25.11

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python -m pip install --upgrade pip
~ % ~/raincoat-venv/bin/python -m raincoat
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
__import__(pkg_name)
File "/home/matt/raincoat-venv/lib/python3.10/site-packages/raincoat/__init__.py", line 1, in <module>
from .raincoat import main
File "/home/matt/raincoat-venv/lib/python3.10/site-packages/raincoat/raincoat.py", line 9, in <module>
from tabulate import tabulate
File "/home/matt/raincoat-venv/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by Gabisonfire** [comment]
Thank you
