### ISSUE TITLE
"unsupported operand type(s)" Error on search

### ISSUE THREAD

**Issue by kahn10** [Gabisonfire/raincoat#8]
After populating my config file I did a test search and got the following error:

```
Searching for "debian"...

Traceback (most recent call last):
  File "/home/conn/.local/bin/raincoat", line 5, in <module>
    from raincoat.raincoat import main
  File "/home/conn/.local/lib/python3.7/site-packages/raincoat/__init__.py", line 3, in <module>
    main()
  File "/home/conn/.local/lib/python3.7/site-packages/raincoat/raincoat.py", line 182, in main
    search(args.search)
  File "/home/conn/.local/lib/python3.7/site-packages/raincoat/raincoat.py", line 150, in search
    'ascii', errors='ignore'), r['CategoryDesc'], r['Seeders'], r['Peers'], download_url, r['Size']))
  File "/home/conn/.local/lib/python3.7/site-packages/raincoat/torrent.py", line 18, in __init__
    self.size = size / 1000
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by Gabisonfire** [comment]
Can you share your config: **Make sure to blank any sensitive data**

**Comment by kahn10** [comment]
{
    "jackett_apikey": "*****************************",
    "jackett_url": "http://127.0.0.1:9117",
    "jackett_indexer": "all",
    "description_length": 100,
    "exclude": "",
    "results_limit": 20,
    "client_url": "http://10.200.200.1:9091/transmission/rpc",
    "display": "grid",
    "torrent_client": "transmission",
    "torrent_client_username": "conn",
    "torrent_client_password": "**********"
}

**Comment by kahn10** [comment]
I also tried it with 
"client_url": "http://10.200.200.1:9091",

**Comment by Gabisonfire** [comment]
I just pushed 0.8, please test the same again with `--verbose` and attach your log file here. `~/.config/Raincoat.log`
